meta_product_name: "Saverz "
meta_title: "Saverz - Help Fund Research While Shopping"
meta_description: "Get Discounts while shopping online. A part of your purchese will fund brazilian researchers."
meta_image: "SaverzMetaImage.png" # should exist in `app/assets/images/`
